# Generated by Django 4.0.1 on 2022-01-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default_product.jpg', upload_to='media'),
        ),
    ]
