# Generated by Django 4.0.1 on 2022-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_category_is_active_contact_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_flower.png', upload_to='media')),
                ('url', models.CharField(blank=True, default=None, max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
    ]
